const newsData = [
  { id: 1, title: "Nueva tecnología revoluciona los smartphones", 
    image: "https://picsum.photos/300/200?random=1", 
    description: "Un avance tecnológico promete cambiar la industria móvil." },
  { id: 2, title: "México gana en torneo internacional", 
    image: "https://picsum.photos/300/200?random=2", 
    description: "La selección mexicana sorprende con su victoria." },
  { id: 3, title: "Descubren exoplaneta habitable", 
    image: "https://picsum.photos/300/200?random=3", 
    description: "Científicos encuentran un planeta con condiciones similares a la Tierra." },
  { id: 4, title: "Avances en la medicina contra el cáncer", 
    image: "https://picsum.photos/300/200?random=4", 
    description: "Nuevas terapias ofrecen esperanza a miles de pacientes." },
  { id: 5, title: "El arte urbano transforma la ciudad", 
    image: "https://picsum.photos/300/200?random=5", 
    description: "Murales coloridos dan nueva vida a barrios olvidados." },
  { id: 6, title: "Tesla lanza nuevo modelo eléctrico", 
    image: "https://picsum.photos/300/200?random=6", 
    description: "Un coche más accesible y con mayor autonomía." },
  { id: 7, title: "Nuevas tendencias en la moda 2025", 
    image: "https://picsum.photos/300/200?random=7", 
    description: "Diseños futuristas marcan la temporada." },
  { id: 8, title: "El turismo espacial gana fuerza", 
    image: "https://picsum.photos/300/200?random=8", 
    description: "Cada vez más empresas apuestan por viajes fuera de la Tierra." },
  { id: 9, title: "Crisis económica impacta en mercados globales", 
    image: "https://picsum.photos/300/200?random=9", 
    description: "Los inversionistas buscan alternativas seguras." },
  { id: 10, title: "Un niño prodigio en matemáticas sorprende al mundo", 
    image: "https://picsum.photos/300/200?random=10", 
    description: "Con solo 12 años resuelve problemas avanzados." },
  { id: 11, title: "La inteligencia artificial en la educación", 
    image: "https://picsum.photos/300/200?random=11", 
    description: "Escuelas integran IA para personalizar el aprendizaje." },
  { id: 12, title: "La música latina conquista el mundo", 
    image: "https://picsum.photos/300/200?random=12", 
    description: "Artistas rompen récords en plataformas digitales." },
  { id: 13, title: "Nuevos récords en los Juegos Olímpicos", 
    image: "https://picsum.photos/300/200?random=13", 
    description: "Atletas superan las expectativas en varias disciplinas." },
  { id: 14, title: "Cuidado del medio ambiente: iniciativas verdes", 
    image: "https://picsum.photos/300/200?random=14", 
    description: "Ciudades implementan proyectos sostenibles." },
  { id: 15, title: "Innovaciones en videojuegos", 
    image: "https://picsum.photos/300/200?random=15", 
    description: "Nuevas consolas y experiencias inmersivas llegan al mercado." }
];

export default newsData;